## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [95]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

## Line Regression 模型

In [96]:
#讀取波士頓房價資料集
boston = datasets.load_boston()
print("type of boston",type(boston))
print("data of boston:",boston.data.shape)
print("target of boston:",boston.target.shape)

type of boston <class 'sklearn.utils.Bunch'>
data of boston: (506, 13)
target of boston: (506,)


In [97]:
#切分資料
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
#載入Line Regression模型
reg = linear_model.LinearRegression()
#帶入訓練
reg.fit(x_train, y_train)
#預測結果
pred = reg.predict(x_test)

In [98]:
reg.coef_

array([-1.15966452e-01,  4.71249231e-02,  8.25980146e-03,  3.23404531e+00,
       -1.66865890e+01,  3.88410651e+00, -1.08974442e-02, -1.54129540e+00,
        2.93208309e-01, -1.34059383e-02, -9.06296429e-01,  8.80823439e-03,
       -4.57723846e-01])

In [99]:
print('(LinearRegression)mean squared error: {}'.format(mean_squared_error(y_test, pred)))
print('(LinearRegression)mean absolute error {}'.format(mean_absolute_error(y_test, pred)))

(LinearRegression)mean squared error: 25.41958712682191
(LinearRegression)mean absolute error 3.3677909837965796


## LASSO Regression 模型

In [100]:
#切分資料
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
#載入Lasso Regression模型
lassoreg = linear_model.Lasso(alpha=1.0)
#帶入訓練
lassoreg.fit(x_train, y_train)
#預測結果
pred = lassoreg.predict(x_test)

In [101]:
lassoreg.coef_

array([-0.06494981,  0.04581458, -0.        ,  0.        , -0.        ,
        1.18140024,  0.01109101, -0.73695809,  0.23350042, -0.01551065,
       -0.69270805,  0.00763157, -0.6927848 ])

In [102]:
print('(Lasso)mean squared error: {}'.format(mean_squared_error(y_test,pred)))
print('(Lasso)mean absolute error {}'.format(mean_absolute_error(y_test, pred)))

(Lasso)mean squared error: 28.95051203673903
(Lasso)mean absolute error 3.5566741401860695


## Ridge Regression 模型

In [103]:
#切分資料
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)
#載入Ridge Regression模型
ridgereg = linear_model.Ridge(alpha=1.0)
#帶入訓練
ridgereg.fit(x_train, y_train)
#預測結果
pred = ridgereg.predict(x_test)

In [104]:
ridgereg.coef_

array([-1.12499445e-01,  4.79562332e-02, -2.40438147e-02,  2.96199458e+00,
       -9.33966118e+00,  3.93079015e+00, -1.73821202e-02, -1.43347691e+00,
        2.75239392e-01, -1.38920708e-02, -8.31116943e-01,  9.15637729e-03,
       -4.66460539e-01])

In [105]:
print('(Ridge)mean squared error: {}'.format(mean_squared_error(y_test,pred)))
print('(Ridge)mean absolute error {}'.format(mean_absolute_error(y_test, pred)))

(Ridge)mean squared error: 25.743684080012603
(Ridge)mean absolute error 3.34386836162158
